# Site settings
author: Kayla Budzeak
title: 
header-img: img/home-bg.png
email: kaylahmg@gmail.com
copyright_name: Kayla Budzeak
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  HeartyRhombus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
